version: '3'

services:
  passport_checker_bot:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .env:/app/.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB_NAME=kdmid_checker
      - POSTGRES_PORT=5432
      - POSTGRES_SSL_MODE=disable
      - POSTGRES_TIMEZONE=Europe/Moscow

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kdmid_checker
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: